### ISSUE TITLE
Front-End Game Service

### ISSUE THREAD

**Issue by mischkowina** [Joooni/42_transcendence#13]
Create a service that feeds the frontend with information on certain ongoing or past matches, first using mock match-objects:
- create mock-objects of games (see mock_users.ts for reference)
- create the service (ng generate service)
- inject the service into home component (for ongoing games) and profile (for past games of that user)
- provide methods getActiveMatches() & getMatchesOfUser(username) in game service
- get active matches onInit for Home Component
- get matches of a user onInit for profile component
- add *ngFor loop in the components .html file to display all relevant games instead of the current placeholders

**Comment by fsemke** [comment]
Done
