### ISSUE TITLE
Add Mockusers to Database

### ISSUE THREAD

**Issue by Joooni** [Joooni/42_transcendence#44]
- create a function to add mockusers to userRepository 
- add a few mock users with different values (online, waiting for game, ingame, yada yada)

**Comment by Triinuj** [comment]
I added two mockusers from user.entity.mock.ts into userRepository, branch mockuser. New users can be added by updating user.entity.mock.ts and users.service.ts

**Comment by Joooni** [comment]
Could we maybe, instead of adding UsersService as a global service, run the database seeding onModuleInit (see https://docs.nestjs.com/fundamentals/lifecycle-events for more info)?

**Comment by Triinuj** [comment]
Sure, I´ll check it out,
